cluster_config:
  chdir: ~/maxwell_output/
  nodes: 1
  partition: psx
  reservation: ''
  time: 00:10:00
  use_cuda: true
contrast:
  coef: 5000.0
  disable: false
  limit: 2000.0
  log: true
general:
  real_time: false
  sleep_time: 0.1
  sum_images: 10
  timeout: 120.0
job_config:
  config_path: test_config.yaml
  data_dir: ~/local_scripts/gixi/tests/data
  dest_name: test_data.h5
  folder_name: dset1
  name: gixi_test
model_config:
  name: save_only_largest_2
parallel:
  max_batch: 10
  parallel_computation: false
polar_config:
  algorithm: 1
  angular_size: 512
  q_size: 1024
postprocessing_config:
  nms_level: 0.1
  score_level: 0.6
program_paths_config:
  local_env: false
q_space:
  distance: 1208.69
  flip_x: false
  flip_y: true
  incidence_angle: 0.5
  pixel_size: 0.2
  q_xy_max: 2.7
  q_xy_num: 1350
  q_z_max: 2.7
  q_z_num: 1350
  size_x: 2048
  size_y: 2048
  wavelength: 0.6888
  y0: 545
  z0: 222
save_config:
  save_img: true
  save_polar_img: true
  save_scores: true
